trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  JAVA_HOME: '/usr/lib/jvm/adoptopenjdk-11-hotspot-amd64'
  GRADLE_HOME: '/usr/share/gradle'
  GRADLE_USER_HOME: '$(System.DefaultWorkingDirectory)/.gradle'

stages:
- stage: BuildAndTest
  displayName: 'Build and Test'
  jobs:
  - job: Build
    displayName: 'Build Job'
    steps:
    - script: |
        sudo apt-get update -y
        sudo apt-get install -y openjdk-11-jdk
        echo "##vso[task.setvariable variable=JAVA_HOME]$(readlink -f /usr/bin/java | sed "s:/bin/java::")"
        java -version
      displayName: 'Install Java JDK 11'
      
    - script: |
        wget https://services.gradle.org/distributions/gradle-7.6-bin.zip
        sudo mkdir /opt/gradle
        sudo unzip -d /opt/gradle gradle-7.6-bin.zip
        echo "##vso[task.setvariable variable=GRADLE_HOME]/opt/gradle/gradle-7.6"
        echo "export PATH=\$PATH:/opt/gradle/gradle-7.6/bin" >> ~/.bashrc
        source ~/.bashrc
        gradle -v
      displayName: 'Install Gradle'
      
    - script: |
        ./gradlew clean test aggregate
      displayName: 'Run Serenity Tests'

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/build/test-results/test/TEST-*.xml'
        failTaskOnFailedTests: true
        testRunTitle: 'Serenity BDD Test Results'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(System.DefaultWorkingDirectory)/target/site/serenity'
        artifactName: 'SerenityReports'
        publishLocation: 'Container'