trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  JAVA_HOME: '/usr/lib/jvm/adoptopenjdk-11-hotspot-amd64'
  GRADLE_HOME: '/usr/share/gradle'
  GRADLE_USER_HOME: '$(System.DefaultWorkingDirectory)/.gradle'

stages:
- stage: BuildAndTest
  displayName: 'Build and Test'
  jobs:
  - job: Build
    displayName: 'Build Job'
    steps:
    - task: UseJava@1
      inputs:
        versionSpec: '11'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
        jdkUserInputPath: '$(JAVA_HOME)'
        checkLatest: false

    - task: Gradle@2
      inputs:
        gradleWrapperFile: 'gradlew'
        options: '-Dorg.gradle.daemon=false'
        tasks: 'clean build'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '11'
        jdkArchitectureOption: 'x64'
    
    - script: |
        ./gradlew clean test aggregate
      displayName: 'Run Serenity Tests'

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/build/test-results/test/TEST-*.xml'
        failTaskOnFailedTests: true
        testRunTitle: 'Serenity BDD Test Results'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(System.DefaultWorkingDirectory)/target/site/serenity'
        artifactName: 'SerenityReports'
        publishLocation: 'Container'